### ISSUE TITLE
ß is normalized incorrectly

### ISSUE THREAD

**Issue by fennelhans** [lamnhan066/string_normalizer#1]
ß is normalized to 'b'. It should be normalized to 'ss'.
https://github.com/vursin/string_normalizer/blob/main/lib/src/data/local.dart#L189

**Comment by lamnhan066** [comment]
Hi @fennelhans, the 'ß' is not the right character with the code 0x1E9E that you mentioned, the right character is 'ẞ'. The 'ß' is [here](https://github.com/vursin/string_normalizer/blob/e2bd3f4d8349eceaa71e1fe2fd18fbe17bf59504/lib/src/data/local.dart#L280) in the database.

I just copied all the codes from http://pinyin.info/unicode/diacritics.html. Please let me know if you have any better sources. Thank you!

**Comment by fennelhans** [comment]
https://en.m.wikipedia.org/wiki/%C3%9F

**Comment by lamnhan066** [comment]
Thank you for your information. I just found that the code is duplicated in the source. I'll update it in the next version.

**Comment by lamnhan066** [comment]
This issue has been resolved since `string_normalizer: ^0.1.0`.
