### ISSUE TITLE
Mathematical Alphanumeric Symbols

### ISSUE THREAD

**Issue by ghnp5** [lamnhan066/string_normalizer#2]
Hey,

Thanks for building this!

Would you consider adding these too?

https://altcodeunicode.com/windows-alt-codes-symbols/alt-codes-math-symbols/
(scroll down to "Alt Codes for Mathematical Alphanumeric Symbols (Letters & Decimal Digits)")

Examples:
https://altcodeunicode.com/alt-codes-math-symbols-bold-script-letters/
https://altcodeunicode.com/alt-codes-math-symbols-sans-serif-letters/
https://altcodeunicode.com/alt-codes-math-symbols-monospace-letters/

There are several pages of symbols that are not being translated/normalized in this project, and should be easy enough to create a mapping of them, because each row of the table mentions also what's the latin version of the letter/number, e.g. "Mathematical bold script capital A".

Many thanks!

**Comment by lamnhan066** [comment]
@ghnp5 Hi, Do we usually need to normalize this kind of character? I don't know whether it’s popular or not to add this because I want to ensure that the package we’re using does not have too much memory usage while running.

**Comment by ghnp5** [comment]
Thank you for your response.
I suppose it depends on the purpose of this project, but I was looking for a normalizer like this, because Spammers/Scammers have been using those symbols to bypass normal URL/Phone Number filters, on my website.

**Comment by lamnhan066** [comment]
I think it’s a good point to add those characters. Can you write a Crawler for it? If not, I’ll try to write one when I have time.
