### ISSUE TITLE
Doesn't work for Greek language

### ISSUE THREAD

**Issue by anpapadakis** [lamnhan066/string_normalizer#3]
Sample Text:

"Όλοι οι άνθρωποι γεννιούνται ελεύθεροι και ίσοι στην αξιοπρέπεια"

**Comment by lamnhan066** [comment]
Hi @anpapadakis

I'm not very familiar with the Greek language. Can you tell me if we need to remove the tones or replace them with Latin words? Thanks!

**Comment by lamnhan066** [comment]
This feature is added in the new version. You can re-open if you have any other related issues.
