### ISSUE TITLE
http and dart_style might not be needed as dependencies by users.

### ISSUE THREAD

**Issue by Leptopoda** [lamnhan066/string_normalizer#6]
Hi there, and thank you for this useful package.
We are considering to use your package but sadly having `dart_style` and `http` pulled in to our dependencies is not ideal for us.
I assume that most users of this package do not need the crawler, so I suggest removing it from `bin` and putting it into the internal `tool` folder.
See the dart package layout for reference: https://dart.dev/tools/pub/package-layout#internal-tools-and-scripts

The CI could still run the script while the dependencies for it could be moved into the ´dev_dependencies` removing them as transitive ones from users of this package.
I know this is a breaking change but would love discussing this further if you disagree.

Thanks for the response.

**Comment by lamnhan066** [comment]
Hi @Leptopoda 

Thank you for your suggestions. If we can run the CI when putting the crawler inside the `tool`, the package should be upgraded to avoid those dependencies.

**Comment by lamnhan066** [comment]
Hi @Leptopoda 

I'll close this issue as it has been resolved in the version `string_normalizer: ^0.3.4`. Please give it a try and re-open this issue if needed. Thank you.
